### ISSUE TITLE
EP 2. STOOL

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/topbobdle#8]
### OVERVIEW
* PM: @zommeworks 
* 주제: 각자 stool을 만들고 들고간다
  * 다리 모듈은 통일하고, 윗부분을 알아서 디자인한다
  * 다리 외의 재료는 알아서 수급한다
  * 앉아서 바베큐 하고 들고간다
  * 바시닝 필요하면 바베큐 끝나고 한다

##### 일정
(참조: https://github.com/zommeworks/topbobdle/issues/9#issuecomment-524626189)
* 8월 말: Kick-off
* 9월 1주차: 스케치
* 9월 2주차: 재료 주문 완료 (공통재료)
* 9월 3주차: 각자 준비
* 9월 4주차: 작업날 시간 안 되는 사람 미리 작업 및 제출
* 10월 1주차: (5일 토요일) 작업날

##### 공통모듈
http://mitem.auction.co.kr/vip?itemNo=B719747768

### NOTE
* 회의록은 여기 epic issue에 댓글 달 것

**Comment by zommeworks** [comment]
### history
* ideation: https://github.com/zommeworks/topbobdle/issues/11#issuecomment-521468458
* 이번엔 초대해서 하자. 확장!확장!
* 초대는 보람누나 희경이 경은이가 관심 가질 것 같다

**Comment by min-kyungeun** [comment]
https://m.ikea.com/kr/ko/catalog/products/art/40289320/

**Comment by min-kyungeun** [comment]
https://m.ikea.com/kr/ko/catalog/products/art/00303752/

**Comment by min-kyungeun** [comment]
공통모듈 구매

| 이름 | 색상 | 크기 | 개수 | 금액 |
|:--:|:--:|:--:|:--:|:--:|
| @min-kyungeun | 호두 | 12| 4| 39,800 |
| @zommeworks | 원목| 15 | 4 | 43,800 |
| @petamind88 | 원목 | 15 | 4 | 43,800 |
| @iboly8283 | 원목 | 15 | 4 | 43,800 |
| @iamhwankim | 원목 | 12 | ~~6~~8 | 79,600 |
| @gmlwjd | 원목 | 12 | 4 | 39,800 |

**Comment by petamind88** [comment]
형근 - 원목 15 4

**Comment by iboly8283** [comment]
보람- 원목/ 15 / 4

**Comment by iamhwankim** [comment]
환-원목/ 12 / 6

**Comment by gmlwjd** [comment]
희정-원목/ 12/ 4

**Comment by zommeworks** [comment]
주문 완료
