### ISSUE TITLE
EP 2. Kick-Off

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/topbobdle#9]
- [x] 카톡방 만들어서 날짜 잡기 (보람, 희정, 경은)
- [x] 공통 모듈 정하기

**Comment by iamhwankim** [comment]
난 벤치같은 스툴

**Comment by petamind88** [comment]
난 고래같은 스툴

**Comment by zommeworks** [comment]
다리 예시 (나는 민경은이다!)
https://m.ikea.com/kr/ko/catalog/products/art/40289320/
https://m.ikea.com/kr/ko/catalog/products/art/00303752/

**Comment by min-kyungeun** [comment]
난 화분도 되는 스툴!

**Comment by zommeworks** [comment]
난 계단 되는 스툴

**Comment by gmlwjd** [comment]
난 가방 되는 스툴

**Comment by iamhwankim** [comment]
http://mitem.auction.co.kr/vip?itemNo=B719747768

**Comment by min-kyungeun** [comment]
http://m.moongori.com/goods/view?no=824283

**Comment by gmlwjd** [comment]
http://m.moongori.com/goods/view?no=815545

**Comment by min-kyungeun** [comment]
- ~9/1 (일) : dimension 고려한 스케치 완료 
- ~9/15 (일) : 모든 부품 주문 완료

**Comment by gmlwjd** [comment]
다리결정!
http://mitem.auction.co.kr/vip?itemNo=B719747768

**Comment by gmlwjd** [comment]
다리결정! 

![A8373342-67A2-4D49-B5AD-1E562FABF423](https://user-images.githubusercontent.com/1700089/63650131-42afbc80-c782-11e9-8787-cd516700ef21.png)
![BB56F699-6FC8-40A7-A5CC-62D21BE9C8CB](https://user-images.githubusercontent.com/1700089/63650134-43485300-c782-11e9-9322-399c2df0f85f.

http://mitem.auction.co.kr/vip?itemNo=B719747768

**Comment by gmlwjd** [comment]
다리결정!
http://mitem.auction.co.kr/vip?itemNo=B719747768
![B2AB9E6C-3EC9-4433-9E65-714D7E5BD33B](https://user-images.githubusercontent.com/1700089/63650150-84406780-c782-11e9-901f-9c234b2f8eb4.png)
![194E65FA-968E-4F12-B526-BBF5641AF78F](https://user-images.githubusercontent.com/1700089/63650151-84406780-c782-11e9-8f58-3efadb258281.jpeg)
